spring:
  application:
    name: passkeys

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: secret

logging:
  level:
    root: INFO
    org.springframework: DEBUG